
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
    // Neon's pooled endpoint doesn't reliably hold `prisma migrate deploy`'s advisory lock across
    // its transaction-mode PgBouncer — this points migrations at the unpooled endpoint instead.
    // Falls back to the pooled URL if DIRECT_URL isn't set anywhere yet, so a missing env var
    // degrades to the old (occasionally-flaky) behavior instead of failing the build outright.
    directUrl: process.env.DIRECT_URL || env("DATABASE_URL"),
  },
});
