-- AlterEnum
ALTER TYPE "ActivityEventType" ADD VALUE 'MOVED_TO_TRASH';
ALTER TYPE "ActivityEventType" ADD VALUE 'RESTORED_FROM_TRASH';
ALTER TYPE "ActivityEventType" ADD VALUE 'MARKED_IMPORTANT';
ALTER TYPE "ActivityEventType" ADD VALUE 'UNMARKED_IMPORTANT';
